# This is a Docker Compose file for running nextcloud with a MariaDB database and Redis cache.
networks:
  backend:
    driver: bridge
  proxy:
    external: true

services:
  # Nextcloud server, reachable only over nginx-proxy
  nextcloud:
    image: nextcloud
    cpus: 4
    container_name: nextcloud
    ports: [ "8080:80" ]
    restart: unless-stopped
    depends_on:
      nextclouddb:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend  # Attach to backend network
      - proxy
    volumes:
      - /pool0/storage/compose/nextcloud/custom_apps:/var/www/html/custom_apps
      - /pool0/storage/compose/nextcloud/config:/var/www/html/config
      - /pool0/storage/nextcloud_data:/var/www/html/data
      - /pool0/storage/compose/nextcloud/servername.conf:/etc/apache2/conf-enabled/servername.conf
    environment:
      - TZ=Europe/Zurich
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis

  # Nextcloud's database
  nextclouddb:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: >
      --transaction-isolation=READ-COMMITTED
      --binlog-format=ROW
      --max_allowed_packet=256M
    networks:
      - backend  # Attach to backend network
    ports: [ "9306:3306" ]
    volumes:
      - /pool0/storage/compose/nextcloud/nextclouddb:/var/lib/mysql
      - /pool0/storage/nextcloud_data:/backup
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    logging:
      options:
        max-size: "10K"
        max-file: "1"    
    networks:
      - backend  # Attach to backend network
    volumes:
      - /pool0/storage/compose/nextcloud/redis:/data  
