# This is a Docker Compose file for running nextcloud with a MariaDB database and Redis cache.
networks:
  backend:
    driver: bridge
  proxy:
    external: true

services:
  # Nextcloud server, reachable only over nginx-proxy
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports: [ "8080:80" ]
    restart: unless-stopped
    depends_on:
      - nextclouddb
      - redis
    networks:
      - backend # Attach to backend network
      - proxy
    volumes:
      - ./custom_apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - /pool0/storage/nextcloud_data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis

  # Nextcloud's database
  nextclouddb:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - backend # Attach to backend network
    volumes:
      - ./nextclouddb:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - backend # Attach to backend network
    volumes:
      - ./redis:/data
