# This is a Docker Compose file for running a MariaDB container with persistent storage.
name: db
services:
  db:
    container_name: mariadb
    restart: always
    image: mariadb:11
    environment: [ MYSQL_ROOT_PASSWORD=geheim ]
    volumes: [ ./mariadb_data:/var/lib/mysql:rw ]
    network_mode: host 