name: transmission
# networks:
#     default:
#         name: transmission
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/data:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/downloads:/downloads #optional
      - CHANGE_TO_COMPOSE_DATA_PATH/watch:/watch #optional
    ports:
      - 192.168.111.11:9999:9091
      - 192.168.1.20:57558:51413
      - 192.168.1.20:57558:51413/udp
    restart: unless-stopped
