volumes:
  torrelay_data:
    external: true
    name: torrelay

services:

  torrelay:
    container_name: torrelay
    build: torrelay
    image: torrelay
    restart: unless-stopped
    logging:
      options:
        max-size: "100K"
        max-file: "1"    
    cpus: 2
    security_opt:
      - no-new-privileges:true
    read_only: true
    stop_grace_period: 2m
    volumes:
      - /pool0/storage/compose/torrelay/torrc:/etc/tor/torrc:ro
      - torrelay_data:/var/lib/tor
    network_mode: host # check if you want this
